### ISSUE TITLE
Remove prefix flag

### ISSUE THREAD

**Issue by JackTemaki** [rwth-i6/rasr#20]
Some cases (e.g. shared dev-clean/dev-other CV dataset for Hybrid training) require merging a bliss corpus while still accessing the same RASR Archives. In order for this to work, we would need to strip the new "merged corpus" name before accessing sequences of the archives example:
Merged Corpus contains entries with "fullname" keys:
```
merged_corpus/corpus_a/recording_1/segment_1
merged_corpus/corpus_b/recording_1/segment_1
```

but the archive A has entries like:
`corpus_a/recording_1/segment_1`

Thus, we need to introduce a parameter for this.

**Comment by ZhouW321** [comment]
you can have 2 corpus element in the xml file and each has different names as the original corpus file

**Comment by JackTemaki** [comment]
So:
```
<?xml version="1.0" encoding="utf-8"?>
<corpus name="dev-clean">
...
</corpus>
<corpus name="dev-other">
...
</corpus>
```
is a valid file?

**Comment by ZhouW321** [comment]
yes, this should be valid to RASR as I recall
